on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_info: ${{ steps.release.outputs.releases_created && toJSON(steps.release.outputs) || '' }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 #v4.4.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  prepare-matrix:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    outputs:
      releases: ${{ steps.releases_map.outputs.releases }}
    steps:
      - name: Prepare releases map
        id: releases_map
        uses: actions/github-script@v7
        with:
          script: |
            const release_info = ${{ fromJson(needs.release-please.outputs.release_info) }};
            const releasedPaths = release_info.paths_released;
            const releases = [];
            for (const releasedPath in releasedPaths) {
              console.log(releasedPath);
              const tag_name = release_info[releasedPath + '--tag_name'];
              const release_url = release_info[releasedPath + '--html_url'];
              const sha = release_info[releasedPath + '--sha'];
              releases.push({
                "tag_name": tag_name,
                "release_url": release_url,
                "sha": sha
              });
            }
            console.log(JSON.stringify(releases));

            core.setOutput('releases', releases);

  post-release:
    needs: [ release-please, prepare-matrix ]
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    strategy:
      matrix:
        path: ${{ fromJSON(needs.prepare-matrix.outputs.releases) }}
    uses: ./.github/workflows/post-release-workflow.yaml
    with:
      tag_name: ${{ matrix.path.tag_name }}
      release_url: ${{ matrix.path.release_url }}
      release_sha: ${{ matrix.path.sha }}
