name: Call post simple workflow

on:
  push:
    branches:
      - test-matrix

jobs:
  matrixs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.result }}

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          const array = [];
          array.push(JSON.stringify({a:"a1",b:"b1"}))
          array.push(JSON.stringify({a:"a2",b:"b2"}))
          array.push(JSON.stringify({a:"a3",b:"b3"}))
          return JSON.stringify({include: array});
      id: matrix
    
  call-workflow:
    needs: matrixs
    strategy:
      matrix: ${{ fromJSON(needs.matrixs.outputs.matrix) }}
    uses: ./.github/workflows/post-simple-workflow.yaml
    with:
      tag_name: ${{ fromJSON(matrix.releases).a }}
      release_url: ${{ fromJSON(matrix.releases).b }}
      release_sha: "demo"